sudo: required

env:
  - VERSION=2.3.0 TAG=latest
  
services:
   - docker

script:
   - ./build.sh build

after_success:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
   - ./build.sh deploy
